<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="17" passed="2" failed="15" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-11T02:16:04 IST" name="Surefire suite" finished-at="2023-05-11T02:16:15 IST" duration-ms="11427">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2023-05-11T02:16:04 IST" name="Surefire test" finished-at="2023-05-11T02:16:15 IST" duration-ms="11427">
      <class name="com.amused.runner.TestRunner">
        <test-method is-config="true" signature="tearUp(org.testng.ITestContext)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:04 IST" name="tearUp" finished-at="2023-05-11T02:16:04 IST" duration-ms="62" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@63c6579]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearUp -->
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:04 IST" name="setUpClass" finished-at="2023-05-11T02:16:06 IST" duration-ms="1599" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:06 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:10 IST" duration-ms="4584" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify the Positive Scenarios"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[ADD Single Object POST API]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[userInvokeTheAddObjectAPI Step is failed due to exception of java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: userInvokeTheAddObjectAPI Step is failed due to exception of java.lang.NullPointerException
at org.testng.Assert.fail(Assert.java:110)
at com.amused.testSteps.testStepDef.userInvokeTheAddObjectAPI(testStepDef.java:79)
at ✽.user add the Object using api Request(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/AddObjectAPI.feature:10)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:10 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:11 IST" duration-ms="388" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verifying the "invalid_DATA_TYPE_FOR_NAME_Field" Negative Scenarios"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[ADD Single Object POST API]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [405]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [405]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at com.amused.testSteps.testStepDef.validateTheStatusCodeIs(testStepDef.java:184)
at ✽.validate the status code is 400(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/AddObjectAPI.feature:29)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:11 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:11 IST" duration-ms="313" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verifying the "Special_Characters_FOR_NAME_Field" Negative Scenarios"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[ADD Single Object POST API]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [405]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [405]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at com.amused.testSteps.testStepDef.validateTheStatusCodeIs(testStepDef.java:184)
at ✽.validate the status code is 400(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/AddObjectAPI.feature:29)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:11 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:11 IST" duration-ms="316" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verifying the "NULL_FOR_NAME_Field" Negative Scenarios"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[ADD Single Object POST API]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [405]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [405]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at com.amused.testSteps.testStepDef.validateTheStatusCodeIs(testStepDef.java:184)
at ✽.validate the status code is 400(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/AddObjectAPI.feature:29)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:11 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:11 IST" duration-ms="259" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that the Getting 400 error When sending POST request with no Body json."]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[ADD Single Object POST API]"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:11 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:12 IST" duration-ms="341" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify GET request to the API endpoint instead of POST"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[ADD Single Object POST API]"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:12 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:12 IST" duration-ms="299" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify the Positive Scenarios"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[Retrieve Single Object GET API]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [405]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at com.amused.testSteps.testStepDef.validateTheStatusCodeIs(testStepDef.java:184)
at ✽.validate the status code is 200(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/GetObjectAPI.feature:7)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:12 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:12 IST" duration-ms="243" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify the Negative Scenarios"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[Retrieve Single Object GET API]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [404] but found [405]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [404] but found [405]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at com.amused.testSteps.testStepDef.validateTheStatusCodeIs(testStepDef.java:184)
at ✽.validate the status code is 404(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/GetObjectAPI.feature:18)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:12 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:13 IST" duration-ms="267" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify the Negative Scenarios"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[Retrieve Single Object GET API]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at com.amused.testSteps.testStepDef.validateTheStatusCodeIs(testStepDef.java:184)
at ✽.validate the status code is 400(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/GetObjectAPI.feature:18)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:13 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:13 IST" duration-ms="392" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that the response is not vulnerable to common web application attacks"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[Retrieve Single Object GET API]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <400> but was <405>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <400> but was <405>.

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at com.amused.testSteps.testStepDef.checkTheSQLInjectionForGetObjectAPI(testStepDef.java:313)
at ✽.Check the "SQL_INJECTION" for get Object API(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/GetObjectAPI.feature:27)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:13 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:13 IST" duration-ms="268" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that the response is not vulnerable to common web application attacks"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[Retrieve Single Object GET API]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <400> but was <405>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <400> but was <405>.

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at com.amused.testSteps.testStepDef.checkTheSQLInjectionForGetObjectAPI(testStepDef.java:321)
at ✽.Check the "XSS" for get Object API(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/GetObjectAPI.feature:27)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:13 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:14 IST" duration-ms="296" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify that the response is not vulnerable to common web application attacks"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[Retrieve Single Object GET API]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <403> but was <405>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <403> but was <405>.

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at com.amused.testSteps.testStepDef.checkTheSQLInjectionForGetObjectAPI(testStepDef.java:330)
at ✽.Check the "CSRF" for get Object API(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/GetObjectAPI.feature:27)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:14 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:14 IST" duration-ms="245" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verifying User ADD Object"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[End to End API Workflow (Add, Get , Update , Patch and Delete)]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[userInvokeTheAddObjectAPI Step is failed due to exception of java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: userInvokeTheAddObjectAPI Step is failed due to exception of java.lang.NullPointerException
at org.testng.Assert.fail(Assert.java:110)
at com.amused.testSteps.testStepDef.userInvokeTheAddObjectAPI(testStepDef.java:79)
at ✽.user add the Object using api Request(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/e2eworkflow.feature:10)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:14 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:14 IST" duration-ms="274" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verifying Added Object is returned in Get Object API"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[End to End API Workflow (Add, Get , Update , Patch and Delete)]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [405]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at com.amused.testSteps.testStepDef.validateTheStatusCodeIs(testStepDef.java:184)
at ✽.validate the status code is 200(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/e2eworkflow.feature:19)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:14 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:14 IST" duration-ms="280" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verifying the User Update the Already created Object"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[End to End API Workflow (Add, Get , Update , Patch and Delete)]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[setNameToObject Step is failed due to exception of java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: setNameToObject Step is failed due to exception of java.lang.NullPointerException
at org.testng.Assert.fail(Assert.java:110)
at com.amused.testSteps.testStepDef.userInvokeTheUpdateObjectAPI(testStepDef.java:144)
at ✽.user update the "ABOVE" Object using api Request(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/e2eworkflow.feature:31)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:14 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:15 IST" duration-ms="439" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verifying the User partially Update the already created Object"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[End to End API Workflow (Add, Get , Update , Patch and Delete)]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[setNameToObject Step is failed due to exception of java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: setNameToObject Step is failed due to exception of java.lang.NullPointerException
at org.testng.Assert.fail(Assert.java:110)
at com.amused.testSteps.testStepDef.userInvokeTheUpdatePartiallyAPI(testStepDef.java:176)
at ✽.user partially update the "ABOVE" Object using api Request(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/e2eworkflow.feature:42)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:15 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-05-11T02:16:15 IST" duration-ms="261" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verifying the User DELETE the already created Object"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[End to End API Workflow (Add, Get , Update , Patch and Delete)]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [405]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at com.amused.testSteps.testStepDef.validateTheStatusCodeIs(testStepDef.java:184)
at ✽.validate the status code is 200(file:///C:/Personal.work/qa-api-automation/src/test/resources/features/e2eworkflow.feature:51)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:15 IST" name="tearDownClass" finished-at="2023-05-11T02:16:15 IST" duration-ms="129" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.amused.runner.TestRunner@2630dbc4]" started-at="2023-05-11T02:16:15 IST" name="tearDown" finished-at="2023-05-11T02:16:15 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.amused.runner.TestRunner -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
